// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LawnCare.StateMachine.Migrations
{
    [DbContext(typeof(SagaDbContext))]
    [Migration("20250724003726_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LawnCare.Shared.MessageContracts.EstimateProcessingState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("current_state");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerInfo")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("customer_info");

                    b.Property<string>("ErrorReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_reason");

                    b.Property<Guid>("EstimateId")
                        .HasColumnType("uuid")
                        .HasColumnName("estimate_id");

                    b.Property<string>("EstimatorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("estimator_id");

                    b.Property<bool>("IsNewCustomer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_new_customer");

                    b.Property<string>("JobDetails")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("job_details");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("version");

                    b.Property<string>("WelcomeEmailError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("welcome_email_error");

                    b.HasKey("CorrelationId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_estimate_processing_states_created_at");

                    b.HasIndex("CurrentState")
                        .HasDatabaseName("ix_estimate_processing_states_current_state");

                    b.HasIndex("EstimateId")
                        .HasDatabaseName("ix_estimate_processing_states_estimate_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_estimate_processing_states_tenant_id");

                    b.ToTable("estimate_processing_states", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
