services:
  lawncare.customerapi:
    image: lawncare.customerapi
    build:
      context: .
      dockerfile: LawnCare.CustomerApi/Dockerfile

  lawncare.statemachine:
    image: lawncare.statemachine
    build:
      context: .
      dockerfile: LawnCare.StateMachine/Dockerfile

  lawncare.statemachine-1:
    image: lawncare.statemachine-1
    build:
      context: .
      dockerfile: LawnCare.StateMachine/Dockerfile

  lawncare.communications:
    image: lawncare.communications
    build:
      context: .
      dockerfile: LawnCare.Communications/Dockerfile

  lawncare.coreapi:
    image: lawncare.coreapi
    build:
      context: .
      dockerfile: LawnCare.CoreApi/Dockerfile

