// <auto-generated />
using System;
using JobService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LawnCare.JobApi.Migrations
{
    [DbContext(typeof(JobDbContext))]
    partial class JobDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LawnCare.JobApi.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("city");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state");

                    b.Property<string>("Street1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("street1");

                    b.Property<string>("Street2")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("street2");

                    b.Property<string>("Street3")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("street3");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("zip_code");

                    b.HasKey("Id")
                        .HasName("pk_address");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("LawnCare.JobApi.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("address_id");

                    b.Property<string>("CellPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cell_phone")
                        .HasComment("Customer's cell phone number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Timestamp when customer was created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by")
                        .HasComment("User who created the customer");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Residential")
                        .HasColumnName("customer_type");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email")
                        .HasComment("Customer's email address");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name")
                        .HasComment("Customer's first name");

                    b.Property<string>("HomePhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("home_phone")
                        .HasComment("Customer's home phone number");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name")
                        .HasComment("Customer's last name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes")
                        .HasComment("Additional notes about the customer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Timestamp when customer was last updated");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by")
                        .HasComment("User who last updated the customer");

                    b.HasKey("CustomerId")
                        .HasName("pk_customers");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("ix_customers_address_id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Customers_Email");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Customers_Status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Customers_TenantId");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Customers_TenantId_Email");

                    b.HasIndex("TenantId", "LastName", "FirstName")
                        .HasDatabaseName("IX_Customers_TenantId_Name");

                    b.ToTable("Customers", "JobService", t =>
                        {
                            t.Property("Id")
                                .HasColumnName("id1");
                        });
                });

            modelBuilder.Entity("LawnCare.JobApi.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActualCost")
                        .HasColumnType("text")
                        .HasColumnName("actual_cost");

                    b.Property<Guid>("ActualServiceAddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("actual_service_address_id");

                    b.Property<Guid?>("AssignedTechnicianId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_technician_id");

                    b.Property<DateTimeOffset?>("CompletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_date")
                        .HasComment("Date job was completed");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Timestamp when job was created");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name")
                        .HasComment("Name of the customer for this job");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description")
                        .HasComment("Detailed description of the work to be performed");

                    b.Property<string>("EstimatedCost")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estimated_cost");

                    b.Property<long>("EstimatedDuration")
                        .HasColumnType("bigint")
                        .HasColumnName("estimated_duration");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset>("RequestedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_date")
                        .HasComment("Date requested by customer");

                    b.Property<DateTimeOffset?>("ScheduledDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_date")
                        .HasComment("Date scheduled for technician");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("special_instructions")
                        .HasComment("Special instructions from customer or management");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Timestamp when job was last updated");

                    b.HasKey("JobId")
                        .HasName("pk_jobs");

                    b.HasIndex("ActualServiceAddressId")
                        .HasDatabaseName("ix_jobs_actual_service_address_id");

                    b.HasIndex("AssignedTechnicianId")
                        .HasDatabaseName("IX_Jobs_AssignedTechnicianId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Jobs_CreatedAt");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_Jobs_CustomerId");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_Jobs_Priority");

                    b.HasIndex("RequestedDate")
                        .HasDatabaseName("IX_Jobs_RequestedDate");

                    b.HasIndex("ScheduledDate")
                        .HasDatabaseName("IX_Jobs_ScheduledDate");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Jobs_Status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Jobs_TenantId");

                    b.HasIndex("TenantId", "CustomerId")
                        .HasDatabaseName("IX_Jobs_TenantId_CustomerId");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_Jobs_TenantId_Status");

                    b.HasIndex("TenantId", "AssignedTechnicianId", "ScheduledDate")
                        .HasDatabaseName("IX_Jobs_TenantId_TechnicianId_ScheduledDate");

                    b.ToTable("Jobs", "JobService", t =>
                        {
                            t.HasCheckConstraint("CK_Jobs_CompletedDate_Future", "\"completed_date\" IS NULL OR \"completed_date\" >= \"created_at\"");

                            t.HasCheckConstraint("CK_Jobs_ScheduledDate_Future", "\"scheduled_date\" IS NULL OR \"scheduled_date\" >= \"created_at\"");
                        });
                });

            modelBuilder.Entity("LawnCare.JobApi.Domain.Entities.JobNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("author")
                        .HasComment("Author of the note (technician, customer, system, etc.)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("content")
                        .HasComment("Content of the note");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Timestamp when note was created");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id")
                        .HasComment("Foreign key to the Job");

                    b.HasKey("Id")
                        .HasName("pk_job_notes");

                    b.HasIndex("Author")
                        .HasDatabaseName("IX_JobNotes_Author");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_JobNotes_CreatedAt");

                    b.HasIndex("JobId")
                        .HasDatabaseName("IX_JobNotes_JobId");

                    b.ToTable("JobNotes", "JobService");
                });

            modelBuilder.Entity("LawnCare.JobApi.Domain.Entities.JobServiceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comment")
                        .HasComment("Optional comment about the service");

                    b.Property<bool>("IsFulfilled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_fulfilled")
                        .HasComment("Whether this service has been fulfilled");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id")
                        .HasComment("Foreign key to the Job");

                    b.Property<decimal>("Price")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("price")
                        .HasComment("Price per unit of service");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity")
                        .HasComment("Quantity of service provided");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("service_name")
                        .HasComment("Name of the service provided");

                    b.HasKey("Id")
                        .HasName("pk_job_service_items");

                    b.HasIndex("IsFulfilled")
                        .HasDatabaseName("IX_JobServiceItems_IsFulfilled");

                    b.HasIndex("JobId")
                        .HasDatabaseName("IX_JobServiceItems_JobId");

                    b.HasIndex("ServiceName")
                        .HasDatabaseName("IX_JobServiceItems_ServiceName");

                    b.ToTable("JobServiceItems", "JobService");
                });

            modelBuilder.Entity("LawnCare.JobApi.Domain.Entities.Customer", b =>
                {
                    b.HasOne("LawnCare.JobApi.Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_customers_address_address_id");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("LawnCare.JobApi.Domain.Entities.Job", b =>
                {
                    b.HasOne("LawnCare.JobApi.Domain.Entities.Address", "ActualServiceAddress")
                        .WithMany()
                        .HasForeignKey("ActualServiceAddressId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_jobs_address_actual_service_address_id");

                    b.Navigation("ActualServiceAddress");
                });

            modelBuilder.Entity("LawnCare.JobApi.Domain.Entities.JobNote", b =>
                {
                    b.HasOne("LawnCare.JobApi.Domain.Entities.Job", null)
                        .WithMany("Notes")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_JobNotes_Job");
                });

            modelBuilder.Entity("LawnCare.JobApi.Domain.Entities.JobServiceItem", b =>
                {
                    b.HasOne("LawnCare.JobApi.Domain.Entities.Job", null)
                        .WithMany("ServiceItems")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_JobRequirements_Job");
                });

            modelBuilder.Entity("LawnCare.JobApi.Domain.Entities.Job", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("ServiceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
