@LawnCare.JobApi_HostAddress = http://localhost:5144

### POST Estimate
POST http://localhost:5144/estimate
Content-Type: application/json

{
  "userId": "user123",
  "tenantId": "729C5768-6534-4C1D-815C-9E15613F1325",
  "customerFirstName": "John",
  "customerLastName": "Doee",
  "customerAddress1": "1223 Main St",
  "customerAddress2": "",
  "customerAddress3": "",
  "customerCity": "Any town",
  "customerState": "CA",
  "customerZip": "90210",
  "customerHomePhone": "555-123-4567",
  "customerCellPhone": "555-987-6543",
  "customerEmail": "john.doemani@example.com",
  "scheduledDate": "2025-08-23T14:00:00.000Z",
  "estimatedCost": 250.00, 
  "estimatedDuration": 16,
  "description": "Weekly lawn maintenance service",
  "services": [
    {
      "serviceName": "Lawn Mowing",
      "quantity": 1,
      "comment": "Front and back yard",
      "price": 100.00
    },
    {
      "serviceName": "Hedge Trimming",
      "quantity": 2,
      "comment": "Front shrubs",
      "price": 75.00
    }
  ]
}

